# Generated by Django 5.2.8 on 2025-11-08 02:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cargos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fecha', models.DateField()),
                ('descripcion', models.TextField(blank=True)),
                ('lugar', models.CharField(blank=True, max_length=100)),
                ('recaudacion_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('gestion', models.ForeignKey(help_text='Gestión organizadora del evento', on_delete=django.db.models.deletion.CASCADE, to='cargos.gestion')),
            ],
        ),
    ]
