# Generated by Django 5.2.8 on 2025-11-08 02:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargos', '0002_initial'),
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='gestion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='cargos.gestion'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='recaudacion_total',
            field=models.FloatField(default=0.0),
        ),
    ]
