# Generated by Django 5.2.8 on 2025-11-08 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0002_alter_evento_gestion_alter_evento_recaudacion_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
