# Generated by Django 5.2.8 on 2025-11-08 02:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del producto', max_length=50)),
                ('stock', models.PositiveIntegerField(default=0, help_text='Stock disponible')),
                ('precio_compra', models.DecimalField(decimal_places=2, help_text='Precio de compra por unidad', max_digits=10)),
                ('precio_venta', models.DecimalField(decimal_places=2, help_text='Precio de venta al público', max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('medio_de_pago', models.CharField(choices=[('Efectivo', 'Efectivo'), ('Mercado Pago', 'Mercado Pago')], default='Efectivo', max_length=20)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('evento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='eventos.evento')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.producto')),
            ],
        ),
    ]
