# Generated by Django 5.2.8 on 2025-11-08 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_venta_precio_unitario_compra_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='precio_compra',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True),
        ),
    ]
